### ISSUE TITLE
No such file to load error when requiring

### ISSUE THREAD

**Issue by blatyo** [reddavis/Distance-Measures#2]
$ ruby -v
    ruby 1.9.2dev (2010-05-31 revision 28117) [x86_64-darwin10.3.1]
$ gem -v
    1.3.7
$ irb
ruby-1.9.2-preview3 > require 'distance_measures'
    LoadError: no such file to load -- distance_measures/euclidean_distance
        from /Users/blatyo/.rvm/gems/ruby-1.9.2-preview3@rails3/gems/distance_measures-0.0.3/lib/distance_measures.rb:4:in `require'
        from /Users/blatyo/.rvm/gems/ruby-1.9.2-preview3@rails3/gems/distance_measures-0.0.3/lib/distance_measures.rb:4:in`<top (required)>'
        from (irb):2:in `require'
        from (irb):2
        from /Users/blatyo/.rvm/rubies/ruby-1.9.2-preview3/bin/irb:17:in`<main>'

**Comment by reddavis** [comment]
Sorry about that. 0.0.4 should work (I have tested it this time ;) )
